
;System CADR made by LISPM at 11/24/22 04:16:37  -*-Mode: Lisp; Package: User; Base: 10.-*-
;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: SYS; CADRLP LISP >"
  '((:COMPILE NIL
     (UA::CONS-LAP-ALLOCATE-ARRAYS NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." UA::MICRO-CODE-SYMBOL-AREA-SIZE))
     (UA::WRITE-VARIOUS-OUTPUTS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" UA::WRITE-MCR)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." UA::CONSLP-OUTPUT-PATHNAME))
     (UA::DEFMIC NIL NIL
      (COMPILER::NOT-USED :IMPLAUSIBLE NIL "The variable ~S is bound but never used." UA::NO-QINTCMP)
      (COMPILER::NOT-USED :IMPLAUSIBLE NIL "The variable ~S is bound but never used." UA::LISP-FUNCTION-P)
      (COMPILER::NOT-USED :IMPLAUSIBLE NIL "The variable ~S is bound but never used." ARGLIST))
     (UA::WRITE-VARIOUS-OUTPUTS-SYSTEM NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" UA::WRITE-MCR-FILE))
     (UA::ASSEMBLE-SYSTEM NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" UA::UA-DO-DEFMIC))
     (UA::ASSEMBLE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" UA::READ-UCODE)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" UA::UA-DO-DEFMIC))
     (UA::ASSEMBLE-READ-FILE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" UA::READ-UCODE))
     (UA::MAKE-ASSEMBLER-STATE-LIST NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" UA::MAKE-CONSTANT-LIST)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: SYS; CDMP LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: SYS; QWMCR LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: IO; FREAD LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: SYS2; USYMLD LISP >"
  '((:COMPILE NIL
     (UA::CC-LOAD-MODULE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR:CC-R-D)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." UA::RACMO)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." UA::RADMO)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." UA::RAAMO)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: CC; LQFMAC LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: CC; LCADMC LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: CC; CC LISP >"
  '((:COMPILE NIL
     (CADR::CC-SELECT-SYMBOL-TABLE NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-FILE-SYMBOLS-LOADED-FROM))
     (CADR::CC-TYPE-IN NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-REPLACE-STATE)
      (COMPILER::BREAK-ARG :OBSOLETE NIL "A symbol as the first argument to BREAK is an obsolete construct;
change it to a string before it stops working: ~S" (BREAK CADR::COND-BARF T))
      (COMPILER::BREAK-ARG :OBSOLETE NIL "A symbol as the first argument to BREAK is an obsolete construct;
change it to a string before it stops working: ~S" (BREAK CADR::INPUT-LOSSAGE-GOBBLING))
      (COMPILER::BREAK-ARG :OBSOLETE NIL "A symbol as the first argument to BREAK is an obsolete construct;
change it to a string before it stops working: ~S" (BREAK CADR::INPUT-LOSSAGE-SPACE)))
     (CADR::CC-LOAD-UCODE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-UCODE-LOADER)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-FILE-SYMBOLS-LOADED-FROM))
     (CADR::CC-LOAD-UCODE-SYMBOLS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-UCODE-LOADER)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-FILE-SYMBOLS-LOADED-FROM))
     (CADR::ASSURE-CC-SYMBOLS-LOADED NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-FILE-SYMBOLS-LOADED-FROM))
     (CADR::CC NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" INIT-DL11-UNIBUS-CHANNEL)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-SETUP-Q-FIELDS)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-GETSYL-READ-TOKEN)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-GETSYL-RCH)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR:DBG-ACCESS-PATH)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::SERIAL-STREAM))
     (CADR::ILONG-TRIAL NIL NIL
      (COMPILER::BREAK-ARG :OBSOLETE NIL "A symbol as the first argument to BREAK is an obsolete construct;
change it to a string before it stops working: ~S" (BREAK CADR::FOO T)))
     (CADR::ILONG-CLEAR NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-READ-C-MEM)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-WRITE-C-MEM))
     (CADR::ILONG-SETUP NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-READ-C-MEM)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-WRITE-C-MEM))
     (CADR::CC-GET-DEFSTRUCT-INDEX NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CAR)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CDR)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-SYMBOL1)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-FIND-PACKAGE)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-SYMBOL)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-FUNCTION-CELL-CONTENTS)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-SAMEPNAMEP)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-LAST))
     ((:PROPERTY CADR::INTON CADR::CC-COLON-CMD) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-WRITE-FUNC-DEST))
     ((:PROPERTY CADR::INTOFF CADR::CC-COLON-CMD) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-WRITE-FUNC-DEST))
     (CADR::CC-DISASSEMBLE-MAPPED-INSTANCE-VAR-NAME NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CAR)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CDR)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-NTH)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-GET)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-ASSQ)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-SYMBOL)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-FEF-DEBUGGING-INFO)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-FLAVOR-MAPPED-INSTANCE-VARIABLES))
     (CADR::CC-DISASSEMBLE-INSTANCE-VAR-NAME NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CAR)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CDR)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-NTH)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-GET)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-ASSQ)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-SYMBOL)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-FEF-DEBUGGING-INFO)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-FLAVOR-ALL-INSTANCE-VARIABLES))
     (CADR::CC-DISASSEMBLE-ARG-NAME NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CURRENT-PACKAGE)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CAR)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CDR)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-NTH)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-ASSQ)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-SYMBOL)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-FEF-DEBUGGING-INFO))
     (CADR::CC-DISASSEMBLE-LOCAL-NAME NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CURRENT-PACKAGE)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CAR)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CDR)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-NTH)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-ASSQ)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-SYMBOL)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-FEF-DEBUGGING-INFO))
     (CADR::QF-SYMEVAL-IN-CLOSURE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CAR)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CDR)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-SYMBOL))
     (CADR::CC-DISASSEMBLE-POINTER NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-MEM-READ)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-FLAVOR-DECODE-SELF-REF-POINTER)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-FEF-FLAVOR-NAME))
     (CADR::CC-DISASSEMBLE-INSTRUCTION NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-MEM-READ)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-INITIAL-AREA-ORIGIN)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-FEF-INSTRUCTION-LENGTH)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-FEF-INSTRUCTION)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-NTH))
     (CADR::CC-DISASSEMBLE-FEF NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-FEF-LIMIT-PC)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-FEF-INITIAL-PC)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-FEF-INSTRUCTION-LENGTH))
     (CADR::CC-CHECK-LEVEL-2-BLOCK NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-PAGE-HASH-TABLE-LOOKUP))
     (CADR::CC-CHECK-MAP NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-LEVEL-1-MAP-FREQUENCIES)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-LEVEL-1-REVERSE-MAP))
     (CADR::CC-DESCRIBE-MEMORY-COPY-OUT-PHT NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-AREA-NUMBER-OF-POINTER))
     (CADR::CC-WHICH-AREA NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-MEM-READ)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-INITIAL-AREA-ORIGIN)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-AREA-NUMBER-OF-POINTER))
     ((:PROPERTY ATOM CADR::CC-COLON-CMD) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-SYMBOL1)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-FIND-PACKAGE))
     (CADR::CC-REMOTE-CONSOLE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-SETUP-Q-FIELDS)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CLEAR-CACHE))
     (CADR::CC-PROCEED NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-SETUP-Q-FIELDS)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CLEAR-CACHE))
     (CADR::CC-STOP NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-SETUP-Q-FIELDS)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CLEAR-CACHE))
     (CADR::CC-STEP NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-SETUP-Q-FIELDS)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CLEAR-CACHE))
     (CADR::CC-CONSOLE-STATUS-DISPLAY NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-ENTER)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-PRINT-ERROR-STATUS)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::DBG-PRINT-STATUS)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-MN-MEM-PAR-P))
     (CADR::CC-RAID NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-RAID-REG))
     (CADR::CC-STORE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-RAID-REG))
     (CADR::CC-PRINT-REG-ADR-CONTENTS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-RAID-REG))
     (CADR::CC-COMPARE-UCODE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-UCODE-LOADER))
     (CADR::CC-LOAD-BOOTSTRAP NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-UCODE-LOADER))
     (CADR:CC-TYPE-OUT NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-PRINT-BITS))
     (CADR::CC-DISASSEMBLE-ADDRESS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-INITIAL-AREA-ORIGIN))
     (CADR::CC-DESCRIBE-MEMORY NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-MEM-READ)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-INITIAL-AREA-ORIGIN))
     (CADR::CC-DESCRIBE-AREAS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-MEM-READ)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-INITIAL-AREA-ORIGIN))
     (CADR::CC-Q-PRINT-U-ENTRY NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-MEM-READ)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-INITIAL-AREA-ORIGIN))
     (CADR::CC-Q-PRINT-STRING NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-MEM-READ)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-ARRAY-SETUP))
     (CADR::CC-DESCRIBE-ADL NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CAR)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CDR))
     (CADR::CC-DESCRIBE-CLOSURE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CAR)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CDR))
     (CADR::CC-DESCRIBE-INSTANCE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CAR)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CDR))
     (CADR::CC-Q-PRINT NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CURRENT-PACKAGE)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-SYMBOL-PACKAGE)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-OBARRAY-NEW-P)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-PKG-SUPER-PACKAGE)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-MEMQ)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-LMSTRING-MSYMBOL-EQUAL)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-PKG-NAME)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-ARRAY-LEADER)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-AR-1)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CAR)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-CDR))
     (CADR::CC-TRACE-THE-STACK NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-ARRAY-LEADER))
     (CADR::CC-REGISTER-DEPOSIT NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-MEM-WRITE)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR:CC-R-D))
     (CADR::CC-REGISTER-EXAMINE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-MEM-READ)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-R-E))
     (CADR::CC-REF-DEFSTRUCT NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-MEM-READ))
     (CADR::CC-FIND-LIST-OR-SYMBOL-HEADER NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-MEM-READ))
     (CADR::CC-STACK-SPACE-BINDING-BLOCK NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-MEM-READ))
     (CADR::CC-STACK-XFER-USTACK NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-MEM-READ))
     (CADR::CC-MEM-READ NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-MEM-READ))
     (CADR:PHYS-MEM-WRITE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::DBG-WRITE-XBUS))
     (CADR:PHYS-MEM-READ NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::DBG-READ-XBUS)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: CC; CCGSYL LISP >"
  '((:COMPILE NIL
     (CADR::CC-GETSYL-READ-TOKEN NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." IMPLODE "is an obsolete function; use strings"))
     (CADR::CC-GETSYL-RCH NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-REPLACE-STATE)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: CC; LCADRD LISP >"
  '((:COMPILE NIL
     (CADR::CC-READ-OBUS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-SERIAL-STREAM)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR:DBG-ACCESS-PATH))
     (CADR::CC-EXECUTE-R NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-SERIAL-STREAM)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR:DBG-ACCESS-PATH))
     (CADR::CC-EXECUTE-W NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-SERIAL-STREAM)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR:DBG-ACCESS-PATH))
     (CADR::CC-EXECUTE-LOAD-DEBUG-IR NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-SERIAL-STREAM)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR:DBG-ACCESS-PATH))
     (CADR::CC-STEP-MACH NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." KBD-TYI-NO-HANG "is an obsolete function; send *TERMINAL-IO* a :TYI-NO-HANG message
or use READ-CHAR-NO-HANG or READ-BYTE-NO-HANG"))
     (CADR:CC-R-D NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::DBG-WRITE-UNIBUS-MAP)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-ZERO-ENTIRE-MACHINE)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::DBG-WRITE-XBUS))
     (CADR::CC-R-E NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::DBG-READ-UNIBUS-MAP)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::DBG-READ-XBUS))
     (CADR::CC-RESET-MACH NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::DBG-RESET)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::DBG-RESET-STATUS))
     (CADR::CC-WRITE-MD NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR:DBG-WRITE)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::DBG-WRITE-UNIBUS-MAP))
     (CADR::SPY-WRITE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CNSUBW)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR:DBG-WRITE))
     (CADR::SPY-READ NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CNSUBR)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR:DBG-READ)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: CC; DIAGS LISP >"
  '((:COMPILE NIL
     (CADR::CC-TEST-MACHINE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::DBG-RESET)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR:DBG-ACCESS-PATH)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::SERIAL-STREAM))
     (CADR::CC-TEST-VMA-DP NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::RAVMA))
     (CADR::CC-RUN-TEST-LOOP NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." KBD-TYI-NO-HANG "is an obsolete function; send *TERMINAL-IO* a :TYI-NO-HANG message
or use READ-CHAR-NO-HANG or READ-BYTE-NO-HANG"))
     (CADR::CC-TEST-LC-AFFECTS-SHIFT NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-SAVED-MICRO-STACK-PTR)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-MICRO-STACK))
     (CADR::CC-TEST-DISPATCH NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-SAVED-MICRO-STACK-PTR)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-MICRO-STACK))
     (CADR::CC-MEM-ZERO NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." KBD-TYI-NO-HANG "is an obsolete function; send *TERMINAL-IO* a :TYI-NO-HANG message
or use READ-CHAR-NO-HANG or READ-BYTE-NO-HANG"))
     (CADR::DC-CLP-NXM NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::DC-CLP-ADR)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::DC-CMD-ADR)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::DC-START-ADR)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::DC-STS-ADR))
     (CADR::CC-MEM-FILL NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." KBD-TYI-NO-HANG "is an obsolete function; send *TERMINAL-IO* a :TYI-NO-HANG message
or use READ-CHAR-NO-HANG or READ-BYTE-NO-HANG"))
     (CADR::CC-MEM-FILL-CHECK NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." KBD-TYI-NO-HANG "is an obsolete function; send *TERMINAL-IO* a :TYI-NO-HANG message
or use READ-CHAR-NO-HANG or READ-BYTE-NO-HANG"))
     (CADR::CC-DISK-REPEAT-OP NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-DISK-WRITE-FCN)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-DISK-ADDRESS)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-DISK-LAST-CMD)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-DISK-LAST-CLP))
     (CADR::CC-CMB-ZAP NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." KBD-TYI-NO-HANG "is an obsolete function; send *TERMINAL-IO* a :TYI-NO-HANG message
or use READ-CHAR-NO-HANG or READ-BYTE-NO-HANG"))
     (CADR::CC-RUN-LOOP NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." KBD-TYI-NO-HANG "is an obsolete function; send *TERMINAL-IO* a :TYI-NO-HANG message
or use READ-CHAR-NO-HANG or READ-BYTE-NO-HANG"))
     (CADR::KEYBOARD-DBG-WRITE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR:DBG-WRITE))
     (CADR::KEYBOARD-DBG-READ NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR:DBG-READ))
     (CADR::CC-DIVIDE-RESTORE-STATE-AND-DIAGNOSE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::DBG-RESET)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-ZERO-ENTIRE-MACHINE))
     (CADR::CC-PARITY-SWEEP NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::DBG-RESET)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-FAST-LOAD-STRAIGHT-MAP))
     (CADR::CC-PARITY-SWEEP-INFO NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-VIRT-ADR-OF-PHYS-ADR)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-AREA-NUMBER-OF-POINTER)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-MEM-READ)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-INITIAL-AREA-ORIGIN)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::QF-MEM-READ-DISK-COPY))
     (CADR::CC-MEM-READ-DISK NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR:CC-DISK-READ))
     (CADR::CC-MEM-TEST-ONE-WORD-TO-DISK NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR:CC-DISK-WRITE))
     (CADR::CC-PDL-BUFFER-PUSH-POP-CHECK NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::DBG-RESET))
     (CADR::CC-GROSS-DATA-TESTS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::DBG-RESET)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: CC; DMON LISP >"
  '((:COMPILE NIL
     (CADR::CC-RUN-MTEST NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-ZERO-ENTIRE-MACHINE)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-UCODE-LOADER)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-MODE-REG)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-UPDATE-DISPLAY-FLAG)
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." KBD-TYI-NO-HANG "is an obsolete function; send *TERMINAL-IO* a :TYI-NO-HANG message
or use READ-CHAR-NO-HANG or READ-BYTE-NO-HANG")
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-SAVED-MD)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-SAVED-VMA)
      (COMPILER::NOT-USED :IMPLAUSIBLE NIL "The variable ~S is bound but never used." CADR::CC-MODE-REG))
     (CADR::CC-MTEST-DING-LOOP NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-SAVED-VMA)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-SAVED-MD))
     (CADR::CC-DIAGNOSE-FLOATING-ONE-RIGHT NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::DBG-READ-XBUS)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: CC; LDBG LISP >"
  '((:COMPILE NIL
     (CADR::DBG-RESET NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-UNIBUS-MAP-TO-MD-OK-FLAG))
     (CADR::DBG-WRITE-UNIBUS-MAP NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-UNIBUS-MAP-TO-MD-OK-FLAG)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: CC; ZERO LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: CC; CADLD LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: CC; QF LISP >"
  '((:COMPILE NIL
     (CADR::QF-MEM-READ-DISK-COPY NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR:CC-DISK-WRITE)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR:CC-DISK-READ)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR:CC-DISK-INIT)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR:CC-DISK-LOWCORE))
     (CADR::QF-OBARRAY-NEW-P NIL NIL
      (COMPILER::NOT-USED :IMPLAUSIBLE NIL "The variable ~S is bound but never used." CADR::PACK))
     (CADR::QF-SWAP-IN NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-CHECK-PAGE-HASH-TABLE-ACCESSIBILITY)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR:CC-DISK-READ))
     (CADR::QF-FINDCORE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR:CC-DISK-WRITE))
     (CADR::QF-PAGE-HASH-TABLE-DELETE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-CHECK-PAGE-HASH-TABLE-ACCESSIBILITY)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: CC; CCWHY LISP >"
  '((:COMPILE NIL
     (CADR::CC-MAIL NIL NIL
      (COMPILER::NOT-USED :IMPLAUSIBLE NIL "The variable ~S is bound but never used." CADR::CC-UPDATE-DISPLAY-FLAG))
     (CADR::WHY-TEXT NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::RAVMA)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-DISK-ADDRESS))
     (CADR::CC-CHECK-SERIOUS-ERROR-STATUS NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR:DBG-ACCESS-PATH)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-DISK-ADDRESS)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-DISK-DA-DESC))
     (CADR::CC-ANALYZE-SOFTWARE-CRASH NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::RAVMA))
     ((:PROPERTY EH::TRANS-TRAP CADR::ETE-HANDLER) NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::RAVMA))
     (CADR::CC-INSTRUCTION-M-SOURCE-REG-ADR NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::RAVMA))
     (CADR::CC-PRINT-ADDRESS-AND-CONTENTS NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::RAVMA))
     (CADR::CC-ANALYZE-DISK-ERR NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR::CC-PRINT-DISK-ERROR-LOG)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: CC; CCDISK LISP >"
  '((:COMPILE NIL
     (CADR::READ-LABEL NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR:CC-DISK-LOWCORE))
     (CADR::FORMAT-DISK-PACK NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-UPDATE-DISPLAY-FLAG))
     (CADR::CC-INITIALIZE-ON-STARTUP NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-FULL-SAVE-VALID)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." CADR::CC-PASSIVE-SAVE-VALID)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: CC; DCHECK LISP >"
  '((:COMPILE NIL
     (CADR::DC-EXEC NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." KBD-CHAR-AVAILABLE "is an obsolete function; use LISTEN or send *TERMINAL-IO* a :LISTEN message"))
     (CADR::DC-EXEC-1 NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." KBD-CHAR-AVAILABLE "is an obsolete function; use LISTEN or send *TERMINAL-IO* a :LISTEN message"))
     (CADR::DC-EXEC-2 NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." KBD-CHAR-AVAILABLE "is an obsolete function; use LISTEN or send *TERMINAL-IO* a :LISTEN message"))
     (CADR::DECODE-TRACK NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." KBD-TYI-NO-HANG "is an obsolete function; send *TERMINAL-IO* a :TYI-NO-HANG message
or use READ-CHAR-NO-HANG or READ-BYTE-NO-HANG")))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: CC; CHPLOC LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: CC; SALVAG LISP >"
  '((:COMPILE NIL)))
