
;System FILE-SYSTEM-UTILITIES made by LISPM at 11/24/22 07:04:10  -*-Mode: Lisp; Package: User; Base: 10.-*-
;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: FILE; FSDEFS LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: FILE; FSSTR LISP >"
  '((:COMPILE NIL
     ((:METHOD FS::LM-STREAM-MIXIN :PROPERTIES) NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." FS::LM-UNSETTABLE-PROPERTIES))
     ((:METHOD FS::LM-OUTPUT-STREAM-MIXIN :AFTER :CLOSE) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" FS::LMFS-CLOSE-FILE)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" FS::LMFS-EXPUNGE-FILE))
     ((:METHOD FS::LM-INPUT-STREAM-MIXIN :AFTER :CLOSE) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" FS::LMFS-CLOSE-FILE))
     ((:METHOD FS::LM-DATA-STREAM-MIXIN :CHANGE-PROPERTIES) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" FS::LMFS-CHANGE-FILE-PROPERTIES))
     ((:METHOD FS::LM-DATA-STREAM-MIXIN :RENAME) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" FS::LMFS-RENAME-FILE))
     ((:METHOD FS::LM-DATA-STREAM-MIXIN :DELETE) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" FS::LMFS-DELETE-FILE))
     ((:METHOD FS::LM-DATA-STREAM-MIXIN :INIT) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" FS::LMFS-FILE-PROPERTIES))
     ((:METHOD FS::LM-STREAM-MIXIN :INIT) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" FS::LMFS-FILE-PROPERTIES)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: FILE; FSGUTS LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: FILE; FSACC LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: TAPE; MTDEFS LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: TAPE; MTSTR LISP >"
  '((:COMPILE NIL
     ((:METHOD FS::MT-FILEHANDLE :OPEN) NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." SI::PUT-ON-ALTERNATING-LIST "is an obsolete function; This function is a crock")))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: TAPE; FDUMP-DEF LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: TAPE; COPY LISP >"
  '((:COMPILE NIL
     (FS::DETERMINE-COPY-DESTINATION NIL NIL
      (SI::BAD-TYPE :IMPLAUSIBLE NIL "The type ~S does not seem to be defined" FS::LOCAL-FILE-PATHNAME)
      (SI::BAD-TYPE :IMPLAUSIBLE NIL "The type ~S does not seem to be defined" FS::REMOTE-LMFILE-PATHNAME))
     (FS::COPY-DESTINATION-EXISTS-P NIL NIL
      (SI::BAD-TYPE :IMPLAUSIBLE NIL "The type ~S does not seem to be defined" FS::LOCAL-FILE-PATHNAME)
      (SI::BAD-TYPE :IMPLAUSIBLE NIL "The type ~S does not seem to be defined" FS::REMOTE-LMFILE-PATHNAME)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: TAPE; MTAUX LISP >"
  '((:COMPILE NIL
     ((:SELECT-METHOD FS::BAND-MAGTAPE-HANDLER :FIND-DISK-PARTITION) NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." GET-FROM-ALTERNATING-LIST "is an obsolete function; use GETF instead"))
     (FS::PLIST-VIA-PATHNAME NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." GET-FROM-ALTERNATING-LIST "is an obsolete function; use GETF instead"))
     (FS::PATHNAME-FROM-PLIST NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." GET-FROM-ALTERNATING-LIST "is an obsolete function; use GETF instead")
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." GET-FROM-ALTERNATING-LIST "is an obsolete function; use GETF instead")
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." GET-FROM-ALTERNATING-LIST "is an obsolete function; use GETF instead")
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." GET-FROM-ALTERNATING-LIST "is an obsolete function; use GETF instead")))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: TAPE; ODUMP LISP >"
  '((:COMPILE NIL
     (FS::RESTORE-PATHNAME-MATCH NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" FS::WILD-STRING-MATCH))
     (FS::DUMP-ONE-FILE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" FS::LM-CONSTRUCT-PLIST)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: FILE; SERVER LISP >"
  '((:COMPILE NIL)))
