
;System CHAOS made by LISPM at 3/12/23 18:43:26  -*-Mode: Lisp; Package: User; Base: 10.-*-
;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: NETWORK; CHAOS; CHSNCP LISP >"
  '((:COMPILE NIL
     (CHAOS::SETUP-MY-ADDRESS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" SI::FIND-PROCESSOR-CONFIGURATION-STRUCTURE)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." SI::*MY-PROC-NUMBER*))
     (CHAOS::TRANSMIT-INT-PKT NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" SI::SHARE-MODE-ACTIVE-P)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" UNIX::PROCESSOR-FOR-HOST-IF-ON-MY-NUBUS)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ETHERNET::GET-ETHERNET-ADDRESS)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" UNIX::TRANSMIT-INT-PKT-TO-SHARING-HOST)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." SI::*OTHER-PROCESSORS*)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." SI::*ETHERNET-HARDWARE-CONTROLLER*)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." SI::*MY-OP*)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." ETHERNET::MY-ETHERNET-ADDRESS)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." ETHERNET::CHAOS-ETHERNET-TYPE)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." ETHERNET::*ETHERNET-CHAOS-PKTS-TRANSMITTED*)
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." ETHERNET::*ETHERNET-CHAOS-PKTS-NOT-TRANSMITTED-LACKING-ETHERNET-ADDRESS*)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: NETWORK; CHAOS; CHUSE LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: NETWORK; CHAOS; CHSAUX LISP >"
  '((:COMPILE NIL
     (CHAOS:POLL-HOSTS NIL NIL
      (COMPILER::NOT-USED :IMPLAUSIBLE NIL "The variable ~S is bound but never used." CHAOS::PKT))
     (CHAOS::USER-ACTIVITY-STRING NIL NIL
      (COMPILER::BAD-TYPE-SPECIFICATION :IMPLAUSIBLE NIL "Error expanding type specification ~S for ~S:~%   ~A" (QUOTE ZWEI::ZMAIL-FRAME) TYPEP #FERROR :PROPERTY-LIST (:TYPE-SPECIFIER ZWEI::ZMAIL-FRAME) :CONDITION-NAMES (FERROR ERROR CONDITION SI::INVALID-TYPE-SPECIFIER) :FORMAT-STRING "~S is not a known type specifier" :FORMAT-ARGS (ZWEI::ZMAIL-FRAME))))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: NETWORK; CHAOS; CHATST LISP >"
  '((:COMPILE NIL
     (CHAOS::%U-WRITE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR:DBG-WRITE))
     (CHAOS::%U-READ NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" CADR:DBG-READ)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: NETWORK; CHAOS; EFTP LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: SITE; HSTTBL LISP >"
  '((:COMPILE NIL)))
