
;System FILE-SYSTEM-UTILITIES made by AMS at 3/22/23 10:59:11  -*-Mode: Lisp; Package: User; Base: 10.-*-
;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: FILE; FSDEFS LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: FILE; FSSTR LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: FILE; FSGUTS LISP >"
  '((:COMPILE NIL
     (FS::LMFS-DIRECTORY-LIST NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." PROCESS-WHOSTATE "is an obsolete function; this function is now SI:PROCESS-WAIT-WHOSTATE")))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: FILE; FSACC LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: TAPE; MTDEFS LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: TAPE; MTSTR LISP >"
  '((:COMPILE NIL
     ((:METHOD FS::MT-FILEHANDLE :OPEN) NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." SI::PUT-ON-ALTERNATING-LIST "is an obsolete function; This function is a crock")
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." SI::PUT-ON-ALTERNATING-LIST "is an obsolete function; This function is a crock")))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: TAPE; FDUMP-DEF LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: TAPE; COPY LISP >"
  '((:COMPILE NIL
     (FS::DETERMINE-COPY-DESTINATION NIL NIL
      (COMPILER::BAD-TYPE-SPECIFICATION :IMPLAUSIBLE NIL "Error expanding type specification ~S for ~S:~%   ~A" (QUOTE FS::LOCAL-FILE-PATHNAME) TYPEP #FERROR :PROPERTY-LIST (:TYPE-SPECIFIER FS::LOCAL-FILE-PATHNAME) :CONDITION-NAMES (FERROR ERROR CONDITION SI::INVALID-TYPE-SPECIFIER) :FORMAT-STRING "~S is not a known type specifier" :FORMAT-ARGS (FS::LOCAL-FILE-PATHNAME))
      (COMPILER::BAD-TYPE-SPECIFICATION :IMPLAUSIBLE NIL "Error expanding type specification ~S for ~S:~%   ~A" (QUOTE FS::REMOTE-LMFILE-PATHNAME) TYPEP #FERROR :PROPERTY-LIST (:TYPE-SPECIFIER FS::REMOTE-LMFILE-PATHNAME) :CONDITION-NAMES (FERROR ERROR CONDITION SI::INVALID-TYPE-SPECIFIER) :FORMAT-STRING "~S is not a known type specifier" :FORMAT-ARGS (FS::REMOTE-LMFILE-PATHNAME)))
     (FS::COPY-DESTINATION-EXISTS-P NIL NIL
      (COMPILER::BAD-TYPE-SPECIFICATION :IMPLAUSIBLE NIL "Error expanding type specification ~S for ~S:~%   ~A" (QUOTE FS::LOCAL-FILE-PATHNAME) TYPEP #FERROR :PROPERTY-LIST (:TYPE-SPECIFIER FS::LOCAL-FILE-PATHNAME) :CONDITION-NAMES (FERROR ERROR CONDITION SI::INVALID-TYPE-SPECIFIER) :FORMAT-STRING "~S is not a known type specifier" :FORMAT-ARGS (FS::LOCAL-FILE-PATHNAME))
      (COMPILER::BAD-TYPE-SPECIFICATION :IMPLAUSIBLE NIL "Error expanding type specification ~S for ~S:~%   ~A" (QUOTE FS::REMOTE-LMFILE-PATHNAME) TYPEP #FERROR :PROPERTY-LIST (:TYPE-SPECIFIER FS::REMOTE-LMFILE-PATHNAME) :CONDITION-NAMES (FERROR ERROR CONDITION SI::INVALID-TYPE-SPECIFIER) :FORMAT-STRING "~S is not a known type specifier" :FORMAT-ARGS (FS::REMOTE-LMFILE-PATHNAME))))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: TAPE; MTAUX LISP >"
  '((:COMPILE NIL
     ((:SELECT-METHOD FS::BAND-MAGTAPE-HANDLER :FIND-DISK-PARTITION) NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." GET-FROM-ALTERNATING-LIST "is an obsolete function; use GETF instead"))
     (FS::PLIST-VIA-PATHNAME NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." GET-FROM-ALTERNATING-LIST "is an obsolete function; use GETF instead"))
     (FS::PATHNAME-FROM-PLIST NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." GET-FROM-ALTERNATING-LIST "is an obsolete function; use GETF instead")
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." GET-FROM-ALTERNATING-LIST "is an obsolete function; use GETF instead")
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." GET-FROM-ALTERNATING-LIST "is an obsolete function; use GETF instead")
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." GET-FROM-ALTERNATING-LIST "is an obsolete function; use GETF instead")))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: TAPE; ODUMP LISP >"
  '((:COMPILE NIL
     (FS::RESTORE-PATHNAME-MATCH NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" FS::WILD-STRING-MATCH))
     (FS::DUMP-ONE-FILE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" FS::LM-CONSTRUCT-PLIST)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: FILE; SERVER LISP >"
  '((:COMPILE NIL)))
