
;System ZMail made by AMS at 3/22/23 11:49:31  -*-Mode: Lisp; Package: User; Base: 10.-*-
;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: ZMAIL; DEFS LISP >"
  '((:COMPILE NIL
     ((:METHOD ZWEI::DRAFT-MSG :AFTER :INIT) NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." ZWEI::*MAIL-HEADER-DELIMITER*))
     (ZWEI::TEMPLATE-INTERVAL NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." ZWEI::*MSG*))
     (ZWEI::TEMPLATE-MSGS NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." ZWEI::*MSG*)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: ZMAIL; TOP LISP >"
  '((:COMPILE NIL
     (ZWEI::INITIALIZE-ZMAIL-FRAME-EDITOR-CLOSURE NIL NIL
      (COMPILER::OBSOLETE :OBSOLETE NIL "~S ~A." PROCESS-PRESET "is an obsolete function; Use the :PRESET message"))
     ((:METHOD ZWEI::ZMAIL-FRAME :MAKE-ZMAIL-BUFFER) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::MAKE-ZMAIL-BUFFER))
     (ZWEI::ADD-HEADER-TO-MSG NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::OUTPUT-HEADER)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PRINT-HEADER))
     (ZWEI::SET-PARSED-MSG-HEADERS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::SET-MSG-SUMMARY-LINE))
     ((:SELECT-METHOD ZWEI::ZMAIL-COMMAND-LIST ZWEI::GET-NEW-MAIL) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::COM-GET-NEW-MAIL))
     ((:SELECT-METHOD ZWEI::ZMAIL-COMMAND-LIST ZWEI::SUMMARY-MOUSE) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::SET-COMMAND-BUTTON)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ZMAIL-SUMMARY-MOUSE))
     ((:SELECT-METHOD ZWEI::ZMAIL-COMMAND-LIST :MOUSE-BUTTON) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::COMMAND-WITH-UNIVERSE-OR-FILTER))
     ((:SELECT-METHOD ZWEI::ZMAIL-COMMAND-LIST ZWEI::MODE-LINE) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::SET-COMMAND-BUTTON))
     ((:SELECT-METHOD ZWEI::ZMAIL-COMMAND-LIST :MENU) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::SET-COMMAND-BUTTON))
     (ZWEI::SET-ZMAIL-USER NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::SET-MAIN-WINDOW-CONFIGURATION))
     ((:INTERNAL ZWEI::RESET-ZMAIL-USER 0) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::SELECT-ZMAIL-BUFFER)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::UPDATE-COMMAND-WHO-LINE-DOCUMENTATION)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::SET-MAIN-WINDOW-CONFIGURATION))
     (ZWEI::UPDATE-ALL-COMMANDS-ASSOCIATED-WITH-OPTIONS-DOCUMENTATION NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::UPDATE-COMMAND-WHO-LINE-DOCUMENTATION))
     (ZWEI::INITIALIZE-ZMAIL NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::INITIALIZE-ZMAIL-COMTABS))
     ((:METHOD ZWEI::ZMAIL-COMMAND-LOOP-MIXIN :PROCESS-COMMAND-CHAR) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::COM-ZMAIL-BREAK)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: ZMAIL; MFILES LISP >"
  '((:COMPILE NIL
     ((:METHOD ZWEI::XGP-HARDCOPY-ZMAIL-BUFFER :AFTER :CLOSE) NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." SI::XGP-QUEUE-FILENAME))
     ((:METHOD ZWEI::HARDCOPY-ZMAIL-BUFFER :ADD-ZMAIL-BUFFER) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::STATUS-LETTER))
     (ZWEI::COM-ZMAIL-HARDCOPY-ALL NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::RECTANGLE-NEAR-COMMAND-MENU))
     (ZWEI::COM-ZMAIL-HARDCOPY-MSG NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::RECTANGLE-NEAR-COMMAND-MENU))
     (ZWEI::ZMAIL-BUFFER-BACKGROUND-SAVE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ZMAIL-BUFFER-SAVE-SETUP))
     (ZWEI::INSERT-NEW-MAIL NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ZMAIL-SELECT-MSG)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::MSG-POINT-PDL-FORWARD-ZMAIL-BUFFER))
     ((:METHOD ZWEI::MAIL-FILE-BUFFER :LOADING-DONE) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::SORT-ZMAIL-BUFFER)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::COMPUTE-CURRENT-MSG-NAME))
     (ZWEI::COM-GET-NEW-MAIL-INTERNAL NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::FOREGROUND-BACKGROUND-FINISH)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::DEFAULT-ZMAIL-MOVE-PATHNAME))
     (ZWEI::GET-NEW-MAIL-FOR-ZMAIL-BUFFER NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ZMAIL-SELECT-NEXT-MSG)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::FOREGROUND-BACKGROUND-FINISH))
     (ZWEI::STARTUP-ZMAIL-BUFFER NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ZMAIL-SELECT-NEXT-MSG))
     ((:METHOD ZWEI::MAIL-FILE-BUFFER :ADD-MSG-TEXT) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ZMAIL-DELETE-MSG))
     ((:METHOD ZWEI::MAIL-FILE-BUFFER :REFORMAT-MSG-HEADER) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PRINT-HEADER))
     ((:METHOD ZWEI::MAIL-FILE-BUFFER :STICKY-OPTIONS) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::SOME-PLIST))
     (ZWEI::ZMAIL-FIND-FILE-NOSELECT-1 NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ABORT-CURRENT-COMMAND))
     ((:METHOD ZWEI::ZMAIL-DISK-BUFFER :PARSE-MSG-TEXT) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PARSE-HEADERS-INTERVAL))
     ((:METHOD ZWEI::ZMAIL-DISK-BUFFER :BEFORE :KILL) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::EXPUNGE-ZMAIL-BUFFER))
     ((:METHOD ZWEI::ZMAIL-BUFFER :KILL) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::UPDATE-COMMAND-WHO-LINE-DOCUMENTATION)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::MSG-POINT-PDL-PURGE))
     (ZWEI::CHOOSE-MAIL-FILE-OPTIONS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::UPDATE-COMMAND-WHO-LINE-DOCUMENTATION)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::TYPEOUT-BEEP-YES-OR-NO-P)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::KILL-ZMAIL-BUFFER)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::CHANGE-ZMAIL-BUFFER-MSGS-SUMMARY-LINES))
     (ZWEI::GET-ZMAIL-FILE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::KILL-ZMAIL-BUFFER))
     (ZWEI::COPY-MSG NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::SOME-PLIST-NOT))
     (ZWEI::SELECT-ZMAIL-BUFFER NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::MSG-POINT-PDL-PUSH)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::UPDATE-COMMAND-WHO-LINE-DOCUMENTATION)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ZMAIL-SELECT-MSG))
     ((:METHOD ZWEI::ZMAIL-BUFFER :ACTIVATE) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::UPDATE-COMMAND-WHO-LINE-DOCUMENTATION)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: ZMAIL; MFHOST LISP >"
  '((:COMPILE NIL
     ((:METHOD ZWEI::ITS-MAIL-FILE-MIXIN :UPDATE-MSG-END) NIL NIL
      (COMPILER::NOT-USED :IMPLAUSIBLE NIL "The variable ~S is bound but never used." ZWEI::FOR-APPEND-P))
     ((:METHOD ZWEI::VMS-MAIL-FILE-MIXIN :REFORMAT-MSG-HEADER) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PRINT-HEADER))
     ((:METHOD ZWEI::UNIX-MAIL-FILE-MIXIN :REFORMAT-MSG-HEADER) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PRINT-ADDRESS-LIST)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PRINT-HEADER))
     (ZWEI::PARSE-UNIX-FROM-HEADER NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PARSE-ADDRESSES))
     ((:METHOD ZWEI::VMS-MAIL-FILE-MIXIN :PARSE-MSG-TEXT) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PARSE-HEADERS-INTERVAL))
     ((:METHOD ZWEI::UNIX-MAIL-FILE-MIXIN :PARSE-MSG-TEXT) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::STRING-EQUAL-START)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PARSE-HEADERS-INTERVAL))
     ((:METHOD ZWEI::UNIX-MAIL-FILE-BUFFER :UPDATE-MSG-OPTIONS-IN-FILE) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::STRING-EQUAL-START)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PRINT-ADDRESS-LIST))
     (ZWEI::PARSE-KEYWORDS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::STRING-FROM-KEYWORDS))
     (ZWEI::PARSE-MSG-NEW-BABYL-STATUS-LINE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::STRING-FROM-KEYWORDS))
     ((:METHOD ZWEI::BABYL-MAIL-FILE-BUFFER :STICKY-OPTIONS) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::SOME-PLIST))
     ((:METHOD ZWEI::ITS-MAIL-FILE-MIXIN :PARSE-MSG-TEXT) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PARSE-ITS-MSG-HEADERS)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: ZMAIL; REFER LISP >"
  '((:COMPILE NIL
     (ZWEI::MAKE-ZMAIL-BUFFER-OF-REFERENCES NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::GET-RECYCLED-TEMP-ZMAIL-BUFFER))
     (ZWEI::EXPAND-UNIVERSE-FUNCTION NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::EXPAND-UNIVERSE))
     (ZWEI::TRACE-REFERENCES-RECURSIVELY NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::GET-UNIVERSE-FUNCTION))
     (ZWEI::GET-MSG-REFERENCES NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::GET-MSG-TEXT-REFERENCES))
     (ZWEI::MSG-IN-REFERENCES NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::SOME-PLIST)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: ZMAIL; LMFILE LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: FILE; ZMAIL LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: ZMAIL; COMNDS LISP >"
  '((:COMPILE NIL
     (ZWEI::STRING-FROM-KEYWORDS NIL NIL
      (COMPILER::FREE-VARIABLE :MISSING-DECLARATION NIL "The variable ~S is used free; assumed special." ZWEI::II))
     (ZWEI::COM-SELECT-ARBITRARY-FORMAT-MAIL-FILE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::READ-ZMAIL-BUFFER-FILENAME))
     (ZWEI::COM-ZMAIL-WHOIS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::CHOOSE-OR-READLINE-ADDRESS)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::STRING-FROM-HEADER))
     (ZWEI::COM-ZMAIL-LIST-BUFFERS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ASSOC-EQUAL))
     (ZWEI::FIND-MSG-FROM-REFERENCE-IN-UNIVERSE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::FIND-MSG-FROM-FILTER))
     (ZWEI::FIND-MSG-FROM-REFERENCE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::MSG-FITS-FILTER-P)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::MAP-OVER-SINGLE-ZMAIL-BUFFER)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::MAP-OVER-DEFINED-UNIVERSE)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::GET-UNIVERSE-FUNCTION))
     (ZWEI::STRING-FOR-MSG-REFERENCE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PRINT-REFERENCE))
     (ZWEI::READ-DIGEST-DESCRIPTION NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PARSE-ADDRESSES))
     (ZWEI::COM-ZMAIL-REPLY-ALL NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ZMAIL-MAIL)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::NORMAL-REPLY))
     (ZWEI::COM-ZMAIL-FORWARD-ALL NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::INITIALIZE-FOR-MAIL)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::INSERT-MSGS-INTO-WINDOW)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ZMAIL-MAIL))
     ((:PROPERTY ZWEI::COM-ZMAIL-MAIL ZWEI::ASSOCIATED-ALL-COMMAND) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::CHOOSE-MAIL-MODE)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::COM-ZMAIL-REDISTRIBUTE-ALL))
     (ZWEI::GET-ZMAIL-BUFFER-ALISTS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::MEMBER-EQUAL))
     (ZWEI::GET-MOVE-ZMAIL-BUFFER NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::SET-COMMAND-BUTTON)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::RECTANGLE-NEAR-COMMAND-MENU)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" TV::APPEND-ITEM-LISTS)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::GET-RECYCLED-TEMP-ZMAIL-BUFFER))
     (ZWEI::CONCATENATE-MSG-TO-MSG NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::UPDATE-MSG-SUMMARY-LINE))
     (ZWEI::COM-ZMAIL-CONCATENATE-ALL NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::UPDATE-MSG-SUMMARY-LINE))
     (ZWEI::CHANGE-MSG-KEYWORDS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::UPDATE-MSG-SUMMARY-LINE))
     (ZWEI::GET-MAIL-FILE-FROM-MSG-BY-FILTERING NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::MSG-FITS-FILTER-P))
     (ZWEI::GET-KEYWORDS-FROM-MSG-BY-FILTERING NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::MSG-FITS-FILTER-P))
     (ZWEI::COM-ZMAIL-SORT NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::DEFAULTED-MULTIPLE-MENU-CHOOSE-NEAR-MENU))
     (ZWEI::COM-ZMAIL-QUIT NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::DEFAULTED-MULTIPLE-MENU-CHOOSE-NEAR-MENU))
     (ZWEI::ZMAIL-BUFFER-PREDICATE-QUERY NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::STATUS-LETTER))
     (ZWEI::COM-ZMAIL-MOUSE-POINT-PDL NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::STATUS-LETTER))
     (ZWEI::CHOOSE-KEYWORDS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::RECTANGLE-NEAR-COMMAND-MENU))
     (ZWEI::CHOOSE-DELETE-MODE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::RECTANGLE-NEAR-COMMAND-MENU))
     (ZWEI::SELECT-ARBITRARY-FORMAT-ZMAIL-BUFFER NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ZMAIL-MENU-CHOOSE))
     (ZWEI::COM-ZMAIL-REPLAY-KEYBOARD-MACRO NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ZMAIL-MENU-CHOOSE))
     (ZWEI::CHOOSE-OTHER-COMMAND NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ZMAIL-MENU-CHOOSE))
     (ZWEI::COM-ZMAIL-MAP NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ZMAIL-MENU-CHOOSE))
     (ZWEI::COM-ZMAIL-MODE-LINE-SCROLL NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ZMAIL-MENU-CHOOSE))
     (ZWEI::COM-ZMAIL-PREVIOUS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ZMAIL-MENU-CHOOSE))
     (ZWEI::COM-ZMAIL-NEXT NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ZMAIL-MENU-CHOOSE))
     (ZWEI::ZMAIL-PRINT-DOC NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ZMAIL-MENU-CHOOSE))
     (ZWEI::COM-ZMAIL-HELP NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::SET-COMMAND-BUTTON)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: ZMAIL; MAIL LISP >"
  '((:COMPILE NIL
     (ZWEI::HEADER-LINE-TYPE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::RFC733-LEXER))
     (ZWEI::FAILED-MAILER-RETRY NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PARSE-ITS-MSG-HEADERS))
     (ZWEI::CANONICALIZE-HEADERS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PARSE-ADDRESSES))
     (ZWEI::SEND-MESSAGE-STRING NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PARSE-ADDRESSES))
     (ZWEI::GET-SEND-HEADERS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PARSE-HEADERS-INTERVAL)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PARSE-ADDRESSES))
     (ZWEI::GET-REDISTRIBUTE-RECIPIENTS NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PARSE-ADDRESSES))
     (ZWEI::XMAILR-REPLY NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PARSE-ADDRESSES))
     (ZWEI::COMSAT-REPLY NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::STRING-EQUAL-START)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PARSE-ADDRESSES))
     (ZWEI::COM-ZMAIL-LOCAL-MAIL-INTERNAL NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::STRING-EQUAL-START))
     (ZWEI::NORMAL-REPLY NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::DEFAULTED-MULTIPLE-MENU-CHOOSE-NEAR-MENU))
     (ZWEI::GET-DRAFT-MSG-FOR-CONTINUE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::RECTANGLE-NEAR-COMMAND-MENU))
     (ZWEI::VALIDATE-DRAFT-MSG-SUMMARY-STRING NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PARSE-HEADERS-INTERVAL)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::SUMMARIZE-RECIPIENTS)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::FIRST-TEXT-LINE))
     (ZWEI::GET-BUG-ARG NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ZMAIL-MENU-CHOOSE))
     (ZWEI::CHOOSE-MAIL-MODE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::ZMAIL-MENU-CHOOSE)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: ZMAIL; WINDOW LISP >"
  '((:COMPILE NIL
     (ZWEI::DEFAULTED-MULTIPLE-MENU-CHOOSE-NEAR-MENU NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" TV::DEFAULTED-MULTIPLE-MENU-CHOOSE))
     (ZWEI::ZMAIL-SUMMARY-MOUSE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::MAKE-ZMAIL-BUFFER-FROM-FILTER-FROM-MSG))
     (ZWEI::CHANGE-ZMAIL-BUFFER-MSGS-SUMMARY-LINES NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::TYPEOUT-BEEP-YES-OR-NO-P))
     ((:PROPERTY ZWEI::CHANGE-MSGS-SUMMARY-LINES ZWEI::WHO-LINE-DOCUMENTATION-UPDATER) NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::TYPEOUT-BEEP-YES-OR-NO-P))
     (ZWEI::FIRST-TEXT-LINE NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::PROBABLE-ITS-HEADER-P)
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" ZWEI::STRING-EQUAL-START)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: ZMAIL; FILTER LISP >"
  '((:COMPILE NIL
     (ZWEI::MENU-GET-ZMAIL-BUFFER-FOR-SELECTION NIL NIL
      (COMPILER:UNDEFINED-FUNCTION-USED :PROBABLE-ERROR NIL "The undefined function ~S was called" TV::APPEND-ITEM-LISTS)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: ZMAIL; PROFIL LISP >"
  '((:COMPILE NIL
     (ZWEI::EDIT-MAIL-FILES-KEYWORDS NIL NIL
      (COMPILER::BAD-TYPE-SPECIFICATION :IMPLAUSIBLE NIL "Error expanding type specification ~S for ~S:~%   ~A" (QUOTE ZWEI::BABYL-MAIL-FILE-BUFFER) TYPEP #FERROR :PROPERTY-LIST (:TYPE-SPECIFIER ZWEI::BABYL-MAIL-FILE-BUFFER) :CONDITION-NAMES (FERROR ERROR CONDITION SI::INVALID-TYPE-SPECIFIER) :FORMAT-STRING "~S is not a known type specifier" :FORMAT-ARGS (ZWEI::BABYL-MAIL-FILE-BUFFER))))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: ZMAIL; MULT LISP >"
  '((:COMPILE NIL
     ((:METHOD TV::MOMENTARY-MULTIPLE-ITEM-LIST-MENU :COMBINED :DEEXPOSE) NIL NIL
      (COMPILER::INSTANCE-VARIABLE-USED-IN-INTERNAL-LAMBDA :UNIMPLEMENTED NIL "The ~:[~;special ~]instance variable ~S of flavor ~S
is being referenced by a lexically closed-over function.
This will not work outside of the dynamic scope of ~S.~:[
This problem will be fixed when Mly's brain hurts a little less.~]" NIL TV:SCREEN-ARRAY TV::MOMENTARY-MULTIPLE-ITEM-LIST-MENU SELF NIL)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: ZMAIL; BUTTON LISP >"
  '((:COMPILE NIL
     ((:METHOD TV::BIG-BUTTON-PANE :COMBINED :DEEXPOSE) NIL NIL
      (COMPILER::INSTANCE-VARIABLE-USED-IN-INTERNAL-LAMBDA :UNIMPLEMENTED NIL "The ~:[~;special ~]instance variable ~S of flavor ~S
is being referenced by a lexically closed-over function.
This will not work outside of the dynamic scope of ~S.~:[
This problem will be fixed when Mly's brain hurts a little less.~]" NIL TV:SCREEN-ARRAY TV::BIG-BUTTON-PANE SELF NIL))
     ((:METHOD TV::BIG-BUTTON-WITH-TOP-OUTSIDE-LABEL-PANE :COMBINED :DEEXPOSE) NIL NIL
      (COMPILER::INSTANCE-VARIABLE-USED-IN-INTERNAL-LAMBDA :UNIMPLEMENTED NIL "The ~:[~;special ~]instance variable ~S of flavor ~S
is being referenced by a lexically closed-over function.
This will not work outside of the dynamic scope of ~S.~:[
This problem will be fixed when Mly's brain hurts a little less.~]" NIL TV:SCREEN-ARRAY TV::BIG-BUTTON-WITH-TOP-OUTSIDE-LABEL-PANE SELF NIL))
     ((:METHOD TV::BUTTON-PANE :COMBINED :DEEXPOSE) NIL NIL
      (COMPILER::INSTANCE-VARIABLE-USED-IN-INTERNAL-LAMBDA :UNIMPLEMENTED NIL "The ~:[~;special ~]instance variable ~S of flavor ~S
is being referenced by a lexically closed-over function.
This will not work outside of the dynamic scope of ~S.~:[
This problem will be fixed when Mly's brain hurts a little less.~]" NIL TV:SCREEN-ARRAY TV::BUTTON-PANE SELF NIL))
     ((:METHOD TV::MEDIUM-BUTTON-PANE :COMBINED :DEEXPOSE) NIL NIL
      (COMPILER::INSTANCE-VARIABLE-USED-IN-INTERNAL-LAMBDA :UNIMPLEMENTED NIL "The ~:[~;special ~]instance variable ~S of flavor ~S
is being referenced by a lexically closed-over function.
This will not work outside of the dynamic scope of ~S.~:[
This problem will be fixed when Mly's brain hurts a little less.~]" NIL TV:SCREEN-ARRAY TV::MEDIUM-BUTTON-PANE SELF NIL))
     ((:METHOD TV::SMALL-BUTTON-PANE :COMBINED :DEEXPOSE) NIL NIL
      (COMPILER::INSTANCE-VARIABLE-USED-IN-INTERNAL-LAMBDA :UNIMPLEMENTED NIL "The ~:[~;special ~]instance variable ~S of flavor ~S
is being referenced by a lexically closed-over function.
This will not work outside of the dynamic scope of ~S.~:[
This problem will be fixed when Mly's brain hurts a little less.~]" NIL TV:SCREEN-ARRAY TV::SMALL-BUTTON-PANE SELF NIL)))))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: ZMAIL; RFC733 LISP >"
  '((:COMPILE NIL)))

;-*-Mode: Lisp; Package: User; Base: 10. -*-
(SI:RELOAD-FILE-WARNINGS
  '#FS::LOGICAL-PATHNAME "SYS: ZMAIL; COMETH LISP >"
  '((:COMPILE NIL
     ((:METHOD ZWEI::UNIVERSE-DEFINITION-FRAME :COMBINED :DEEXPOSE) NIL NIL
      (COMPILER::INSTANCE-VARIABLE-USED-IN-INTERNAL-LAMBDA :UNIMPLEMENTED NIL "The ~:[~;special ~]instance variable ~S of flavor ~S
is being referenced by a lexically closed-over function.
This will not work outside of the dynamic scope of ~S.~:[
This problem will be fixed when Mly's brain hurts a little less.~]" NIL TV:SCREEN-ARRAY ZWEI::UNIVERSE-DEFINITION-FRAME SELF NIL))
     ((:METHOD ZWEI::ZMAIL-FILTER-FRAME :COMBINED :DEEXPOSE) NIL NIL
      (COMPILER::INSTANCE-VARIABLE-USED-IN-INTERNAL-LAMBDA :UNIMPLEMENTED NIL "The ~:[~;special ~]instance variable ~S of flavor ~S
is being referenced by a lexically closed-over function.
This will not work outside of the dynamic scope of ~S.~:[
This problem will be fixed when Mly's brain hurts a little less.~]" NIL TV:SCREEN-ARRAY ZWEI::ZMAIL-FILTER-FRAME SELF NIL))
     ((:METHOD ZWEI::ZMAIL-FRAME :COMBINED :DEEXPOSE) NIL NIL
      (COMPILER::INSTANCE-VARIABLE-USED-IN-INTERNAL-LAMBDA :UNIMPLEMENTED NIL "The ~:[~;special ~]instance variable ~S of flavor ~S
is being referenced by a lexically closed-over function.
This will not work outside of the dynamic scope of ~S.~:[
This problem will be fixed when Mly's brain hurts a little less.~]" NIL TV:SCREEN-ARRAY ZWEI::ZMAIL-FRAME SELF NIL))
     ((:METHOD ZWEI::ZMAIL-COMMAND-MENU-PANE :COMBINED :DEEXPOSE) NIL NIL
      (COMPILER::INSTANCE-VARIABLE-USED-IN-INTERNAL-LAMBDA :UNIMPLEMENTED NIL "The ~:[~;special ~]instance variable ~S of flavor ~S
is being referenced by a lexically closed-over function.
This will not work outside of the dynamic scope of ~S.~:[
This problem will be fixed when Mly's brain hurts a little less.~]" NIL TV:SCREEN-ARRAY ZWEI::ZMAIL-COMMAND-MENU-PANE SELF NIL)))))
