;;; -*- Mode:Lisp; Readtable:ZL; Package:SI; Base:10; Patch-File:T -*-
;;; Patch file for System version 99.27
;;; Reason:
;;;  Foo
;;; Written 12-Apr-85 22:47:58 by mly,
;;; while running on Lisp Machine Twelve from band 1
;;; with System 99.24, CADR 4.2, Experimental ZMail 54.4, MIT-Specific 23.0, Experimental Local-File 52.0, microcode 320, GC@2, Local-file.


; From file OZ:KANSAS:<L.ZWEI>FILES.LISP.196 at 28-Feb-85 22:00:35
#10R ZWEI#:
(COMPILER-LET ((*PACKAGE* (PKG-FIND-PACKAGE "ZWEI")))
  (COMPILER::PATCH-SOURCE-FILE "SYS: ZWEI; FILES  "


(DEFUN READ-DIRECTORY-NAME (PROMPT PATHNAME &KEY (DEFAULT-NAME :WILD)
						 (DEFAULT-TYPE :WILD)
						 (DEFAULT-VERSION :WILD))
  "Read a pathname to pass to FS:DIRECTORY-LIST.
Prompt with PROMPT, a string probably ending in a colon.
PATHNAME gives the defaults for host, device, directory.
WILDP gives the default used for the other components;
 normally :WILD, but could be NIL."
  (WITH-STACK-LIST (DEFS :DEFAULT-NAME DEFAULT-NAME
		         :DEFAULT-TYPE DEFAULT-TYPE
			 :DEFAULT-VERSION DEFAULT-VERSION)
    (LET ((TYPEIN (APPLY #'READ-UNDEFAULTED-DIRECTORY-STRING PROMPT PATHNAME DEFS)))
      (COND ((EQUAL TYPEIN "")
	     (PUSH-ON-HISTORY PATHNAME *PATHNAME-ARGUMENT-HISTORY*)
	     PATHNAME)
	    (T
	     (SETQ PATHNAME (APPLY #'FS:MERGE-PATHNAME-COMPONENTS TYPEIN PATHNAME DEFS))
	     (PUSH-ON-HISTORY PATHNAME *PATHNAME-ARGUMENT-HISTORY*)
	     PATHNAME)))))

))

; From file OZ:OZ:<MLY.LL>QRAND.LISP.7 at 6-Mar-85 00:53:07
#8R SYSTEM-INTERNALS#:
(COMPILER-LET ((*PACKAGE* (PKG-FIND-PACKAGE "SYSTEM-INTERNALS")))
  (COMPILER::PATCH-SOURCE-FILE "SYS: SYS; QRAND  "

(remprop 'symbol-plist 'si::setf-method)
(remprop 'symbol-plist 'si::locf-method)

(DEFSUBST SYMBOL-PLIST (SYMBOL)
  "Return the contents of the property list of SYMBOL."
  (CONTENTS (PROPERTY-CELL-LOCATION SYMBOL)))

(DEFUN PLIST (OBJECT-WITH-PROPERTY-LIST)
  "Return the contents of the property list of OBJECT-WITH-PROPERTY-LIST,
which may be a symbol, an instance supporting the :PROPERTY-LIST operation,
or a locative or cons cell whose cdr is the property list."
 (ETYPECASE OBJECT-WITH-PROPERTY-LIST
   (SYMBOL (CONTENTS (LOCF (SYMBOL-PLIST OBJECT-WITH-PROPERTY-LIST))))
   ((OR CONS LOCATIVE) (CDR OBJECT-WITH-PROPERTY-LIST))
   ((OR INSTANCE NAMED-STRUCTURE) (SEND OBJECT-WITH-PROPERTY-LIST :PROPERTY-LIST))))

;; used by (locf (plist ...))
(DEFUN PLIST-LOCATION (OBJECT-WITH-PROPERTY-LIST)
  (ETYPECASE OBJECT-WITH-PROPERTY-LIST
    (SYMBOL (PROPERTY-CELL-LOCATION OBJECT-WITH-PROPERTY-LIST))
    ((OR CONS LOCATIVE) (LOCF (CDR OBJECT-WITH-PROPERTY-LIST)))
    ((OR INSTANCE NAMED-STRUCTURE) (SEND OBJECT-WITH-PROPERTY-LIST :PROPERTY-LIST-LOCATION))))

(DEFUN SETPLIST (OBJECT-WITH-PROPERTY-LIST VALUE)
  (ETYPECASE OBJECT-WITH-PROPERTY-LIST
    (SYMBOL (SETF (SYMBOL-PLIST OBJECT-WITH-PROPERTY-LIST) VALUE))
    ((OR CONS LOCATIVE) (SETF (CDR OBJECT-WITH-PROPERTY-LIST) VALUE))
    ((OR INSTANCE NAMED-STRUCTURE)
     (SEND OBJECT-WITH-PROPERTY-LIST :SET-PROPERTY-LIST VALUE))))


))

