;;; -*- Mode:Lisp; Readtable:ZL; Package:USER; Base:8; Patch-File:T -*-
;;; Patch file for System version 100.18
;;; Reason:
;;;  Make sure we don't try to a ZWEI host (ED-FILE, ED-BUFFER, ...) as a SI:ASSOCIATED-MACHINE.
;;; Written 6-Jun-23 17:30:26 by ams,
;;; while running on Lisp Machine One from band 2
;;; with Experimental System 100.13, Hacks by AMS 2.0, microcode 323, WIP.



; From file FC: /sys/network/host.lisp at 6-Jun-23 17:30:26
#8R SYSTEM-INTERNALS#:
(COMPILER-LET ((*PACKAGE* (PKG-FIND-PACKAGE "SYSTEM-INTERNALS")))
  (COMPILER::PATCH-SOURCE-FILE "FC: //sys//network//host"

(DEFUN SET-LOCAL-HOST-VARIABLES (&AUX ELEM)
  (IF LOCAL-HOST
      (SETQ LOCAL-HOST-NAME (SEND LOCAL-HOST :NAME)))
  (COND ((SETQ ELEM (ASSOC-EQUALP LOCAL-HOST-NAME MACHINE-LOCATION-ALIST))
	 (LET (TEM)
	   (SETF `(LOCAL-HOST-NAME ,LOCAL-PRETTY-HOST-NAME ,LOCAL-FINGER-LOCATION
				   ,LOCAL-FLOOR-LOCATION ,ASSOCIATED-MACHINE
				   ,TEM)
		 ELEM)
	   (SETQ ASSOCIATED-MACHINE (FS:GET-PATHNAME-HOST ASSOCIATED-MACHINE))
	   (SETQ HOST-OVERRIDDEN-SITE-OPTION-ALIST NIL)  ;In case error in EVAL.
	   (SETQ HOST-OVERRIDDEN-SITE-OPTION-ALIST
		 (LOOP FOR (KEY EXP) IN TEM
		       COLLECT `(,KEY . ,(EVAL EXP))))))
	(T
	 (SETQ LOCAL-PRETTY-HOST-NAME "Unknown"
	       LOCAL-FINGER-LOCATION "(Unknown)"
	       LOCAL-FLOOR-LOCATION '(UNKNOWN 0)
	       ASSOCIATED-MACHINE
	       (IF (GET-SITE-OPTION :DEFAULT-ASSOCIATED-MACHINE)
		   (FS:GET-PATHNAME-HOST (GET-SITE-OPTION :DEFAULT-ASSOCIATED-MACHINE))
		 ;; Make sure we don't use a ZWEI host (buffers etc)
		 (CAR (REM-IF #'(LAMBDA (H)
				  (CONDITION-CASE ()
				      (EQ (SEND H :SYSTEM-TYPE) :ZWEI)
				    (ERROR NIL)))
			      FS:*PATHNAME-HOST-LIST*)))
	       HOST-OVERRIDDEN-SITE-OPTION-ALIST NIL)))
  (INITIALIZATIONS 'SITE-OPTION-INITIALIZATION-LIST T))
))
