;-*-Mode:Lisp; Package: USER; Base:8 -*-
;These systems are declared in SYS: SYS; SYSDCL

(DEFSYSTEM LFS
  (:PATHNAME-DEFAULT "SYS: FILE2;")
  (:NICKNAMES "LMFILE")
  (:PACKAGE FILE-SYSTEM)
  (:PATCHABLE NIL "LMFILE")
  (:COMPONENT-SYSTEMS LMFILE-SERVER)
  (:MODULE DEFS ("DEFS" "PATHNM"))
  (:MODULE LFS ("PACK" "FREE" "IO" "FILES" "GC" "AREA"
		"NODE" "LINK" "PDP10" "CHGNOD" "SALVAG"
		"ANYDIR" "SPCDIR" "DIREAD" "COMPLT"
		"STREAM" "DUMP"))
  (:MODULE ZMAIL ("ZMAIL;LMFILE") :PACKAGE ZWEI)
  (:COMPILE-LOAD DEFS)
  (:COMPILE-LOAD ZMAIL (:FASLOAD DEFS))
  (:COMPILE-LOAD LFS (:FASLOAD DEFS)))

(DEFSYSTEM LMFILE-SERVER
  (:NAME "LMFILE-Server")
  (:NICKNAMES "Server")
  (:SHORT-NAME "SVR")
  (:PATHNAME-DEFAULT "SYS: FILE2;")
  (:PACKAGE FILE-SYSTEM)
  (:MODULE DEFS "RMDEFS")
  (:MODULE MAIN ("SERVER" "MAISER"))
  (:COMPILE-LOAD DEFS)
  (:COMPILE-LOAD MAIN (:FASLOAD DEFS)))

(DEFSYSTEM LMFILE-REMOTE
  (:NAME "LMFILE-Remote")
  (:NICKNAMES "Remote")
  (:SHORT-NAME "RM")
  (:NOT-IN-DISK-LABEL)
  (:PATHNAME-DEFAULT "SYS: FILE2;")
  (:PATCHABLE NIL "REMOTE")
  (:PACKAGE FILE-SYSTEM)
  (:MODULE DEFS ("RMDEFS" "PATHNM"))
  (:MODULE MAIN "REMOTE")
  (:MODULE ZMAIL "ZMAIL; LMFILE" :PACKAGE ZWEI)
  (:COMPILE-LOAD DEFS)
  (:COMPILE-LOAD ZMAIL (:FASLOAD DEFS))
  (:COMPILE-LOAD MAIN (:FASLOAD DEFS) (:FASLOAD DEFS)))