;;; -*-Mode:Lisp;Package:FS;Base:10;Fonts:MEDFNT-*-

(DEFVAR *MIT-HACKERS*
	'("RMS" "MLY" "DANIEL.G.MLY" "PGS" "AKR"))

(DEFUN (:PROPERTY :LMI-WRITTEN COPY-FILTER) (PLIST)
  (NOT (MEMBER (GET PLIST ':AUTHOR) *MIT-HACKERS*)))
