;-*- Mode:Text; Fonts:(TR12 CPTFONT TR12I HL12B TR12B TR12BI); Readtable:T; Base:10 -*-

System NN is now released.  It uses microcode version NNN.

Contents of the rest of this file:

4   Incompatible Changes* 
4   Window System Changes* 
4   User Interface Changes* 
4   Editor Changes* 

4Incompatible Changes* 

1] 4Something or other about an Incompatible Change.** 

4Window System Changes* 

4User Interface Changes* 

4Editor Changes* 
