;;; -*- Mode: Lisp; Package: ZWEI; Base: 8.; Patch-File: T -*-
;;; Written 10-Feb-84 23:47:04 by Mly,
;;; Reason: Survey bug (~ again)
;;; while running on Lisp Machine Eighteen from band 6
;;; with System 98.34, CADR 3.6, ZMail 53.10, MIT-Specific 22.0, microcode 306, ZM MIT.



; From file FILTER.LISP PS:<L.ZMAIL> OZ:
#8R ZWEI#:
(COMPILER-LET ((PACKAGE (PKG-FIND-PACKAGE "ZWEI")))
  (COMPILER#:PATCH-SOURCE-FILE "SYS: ZMAIL; FILTER  "

(DEFUN SURVEY-FROM-FILTER (MAP-FUNCTION MAP-ARG FILTER-FUNCTION FILTER-ARG
			   &AUX TERMINAL-IO)
  (IF (TV:SHEET-EXPOSED-P *SUMMARY-WINDOW*)
      (SETQ TERMINAL-IO (FUNCALL *SUMMARY-WINDOW* ':TYPEOUT-WINDOW))
      (SETQ TERMINAL-IO (WINDOW-TYPEOUT-WINDOW *WINDOW*))
      (FUNCALL STANDARD-OUTPUT ':LINE-OUT *SUMMARY-WINDOW-LABEL*))
;  (TV:WINDOW-CALL (TERMINAL-IO)		;For **MORE** blinking
     (LET ((*N* 0))
       (FUNCALL MAP-FUNCTION MAP-ARG FILTER-FUNCTION FILTER-ARG
		#'(LAMBDA (MSG STREAM &AUX STATUS)
		    (SETQ STATUS (ASSURE-MSG-PARSED MSG))
		    (FUNCALL STREAM ':TRUNCATED-ITEM 'SUMMARY-LINE MSG "~\ZWEI:ARROW\~3D~C~A"
			     (EQ MSG *MSG*) (SETQ *N* (1+ *N*)) (STATUS-LETTER STATUS)
			     (MSG-SUMMARY-LINE MSG))
		    (FUNCALL STREAM ':TYO #\CR))
		STANDARD-OUTPUT))
    (FUNCALL STANDARD-OUTPUT ':LINE-OUT "Done.")
  (CHECK-FOR-TYPEOUT-WINDOW-TYPEOUT)
  DIS-NONE)

))
