;;; -*- Mode: Lisp; Package: ZWEI; Base: 8.; Patch-File: T -*-
;;; Patch file for ZMail version 53.6
;;; Reason: 
;;; Reason: "Compile init file" is willing to recompile instead.
;;; Defaulting non-ITS pathname from FOO BABYL bug.
;;; Mail files remembered in init file menu duplications fixed.
;;; Bug in editing remembered universes list.
;;; Written 12/28/83 03:30:39 by RMS,
;;; while running on Lisp Machine Two from band 6
;;; with Don't-dump-a-band! Inconsistent (unreleased patches loaded) System 98.16, CADR 3.2, Experimental ZMail 53.5, MIT-Specific 22.0, microcode 305, ZM MIT.



; From file PROFIL.LISP SRC:<L.ZMAIL> OZ:
#8R ZWEI#:
(COMPILER-LET ((PACKAGE (PKG-FIND-PACKAGE "ZWEI")))
  (COMPILER#:PATCH-SOURCE-FILE "SYS: ZMAIL; PROFIL  "

(DEFUN MAKE-INIT-FILE-BE-COMPILED ()
  "Switch to using a compiled init file if not already so, and recompile if needed."
  (UNLESS (PROFILE-BUFFER-PROFILE-COMPILE-TICK *INTERVAL*)
    (LET* ((DEFAULT (FUNCALL (FS:USER-HOMEDIR) ':NEW-PATHNAME
			     ':NAME "ZMAIL" ':TYPE ':LISP ':VERSION ':NEWEST))
	   (PATHNAME))
      (DO () (())
        (SETQ PATHNAME
	      (READ-DEFAULTED-PATHNAME "Pathname for source file: " DEFAULT))
	(UNLESS (EQ PATHNAME (ZMAIL-INIT-FILE-PATHNAME))
	  (RETURN))
	(BEEP)
	(FORMAT QUERY-IO "~&That is where the compiled version must go.  Try again.")
	(SEND QUERY-IO ':WAIT-FOR-INPUT-WITH-TIMEOUT 30.))
      (SETF (BUFFER-PATHNAME *INTERVAL*) PATHNAME)
      (SETF (BUFFER-GENERIC-PATHNAME *INTERVAL*) (FUNCALL PATHNAME ':GENERIC-PATHNAME))
      (SEND *INTERVAL* ':RENAME (FUNCALL PATHNAME ':STRING-FOR-EDITOR))
      ;; Say source needs to be saved.
      (SETF (BUFFER-FILE-ID *INTERVAL*) T)
      ;; Say compilation is very out-of-date.
      (SETF (PROFILE-BUFFER-PROFILE-COMPILE-TICK *INTERVAL*) -1)))
  (COMPILE-ZMAIL-INIT-FILE))

))

; From file COMNDS.LISP SRC:<L.ZMAIL> OZ:
#8R ZWEI#:
(COMPILER-LET ((PACKAGE (PKG-FIND-PACKAGE "ZWEI")))
  (COMPILER#:PATCH-SOURCE-FILE "SYS: ZMAIL; COMNDS  "

(DEFUN DEFAULT-ZMAIL-MOVE-PATHNAME ()
  (SEND (LET ((FS:*ALWAYS-MERGE-TYPE-AND-VERSION* T))
	  (COND ((AND *DEFAULT-MOVE-ZMAIL-BUFFER*
		      (ZMAIL-BUFFER-DISK-P *DEFAULT-MOVE-ZMAIL-BUFFER*))
		 (FUNCALL *DEFAULT-MOVE-ZMAIL-BUFFER* ':NAME))
		(*DEFAULT-MOVE-MAIL-FILE-NAME*
		 (FS:MERGE-PATHNAME-DEFAULTS *DEFAULT-MOVE-MAIL-FILE-NAME*
					     *ZMAIL-PATHNAME-DEFAULTS*))
		(T (FS:MERGE-PATHNAME-DEFAULTS USER-ID (FS:USER-HOMEDIR) ':XMAIL))))
	;; Make version be NIL just in case it used to be :UNSPECIFIC
	;; (such as in an ITS pathname with TYPE = "BABYL")
	;; because it is going to be used with FS:*ALWAYS-MERGE-TYPE-AND-VERSION* non-NIL.
	':NEW-VERSION NIL))

))

; From file PROFIL.LISP SRC:<L.ZMAIL> OZ:
#8R ZWEI#:
(COMPILER-LET ((PACKAGE (PKG-FIND-PACKAGE "ZWEI")))
  (COMPILER#:PATCH-SOURCE-FILE "SYS: ZMAIL; PROFIL  "

(DEFMETHOD (ZMAIL-PROFILE-BUFFER :RESECTIONIZE) (&REST IGNORE)
  (RESECTIONIZE-FILE-BUFFER SELF NIL 'ZMAIL-PROFILE-BUFFERS))

))

; From file PROFIL.LISP SRC:<L.ZMAIL> OZ:
#8R ZWEI#:
(COMPILER-LET ((PACKAGE (PKG-FIND-PACKAGE "ZWEI")))
  (COMPILER#:PATCH-SOURCE-FILE "SYS: ZMAIL; PROFIL  "

(DEFUN EDIT-PROFILE-REMEMBERED-MAIL-FILES (NEAR-MODE)
  (LET ((ZMAIL-BUFFER-ALIST (GET-ZMAIL-BUFFER-ALISTS T))
	(ACTIVE-LIST NIL)
	TEM)
    (SETQ ZMAIL-BUFFER-ALIST (DELQ (RASSQ *PRIMARY-ZMAIL-BUFFER* ZMAIL-BUFFER-ALIST)
				   ZMAIL-BUFFER-ALIST))
    ;; ACTIVE-LIST gets all the buffers (or pathnames, if file is not loaded)
    ;; that are remembered in the init file as of now.
    (DOLIST (FILE-NAME *OTHER-MAIL-FILE-NAMES*)
      (PUSH (CDR (OR (RASSQ FILE-NAME ZMAIL-BUFFER-ALIST)
		     (CLI:RASSOC (SEND FILE-NAME ':NEW-VERSION NIL)
				 ZMAIL-BUFFER-ALIST
				 ':KEY 'BUFFER-PATHNAME)))
	    ACTIVE-LIST))
    (MULTIPLE-VALUE (ZMAIL-BUFFER-ALIST ACTIVE-LIST)
      (ZMAIL-MULTIPLE-MENU-CHOOSE ZMAIL-BUFFER-ALIST (NREVERSE ACTIVE-LIST)
				  'MULTIPLE-MENU-NEW-PATHNAME NEAR-MODE
				  "Mail files to be remembered in init file"))
    (SETQ ACTIVE-LIST (LOOP FOR X IN ZMAIL-BUFFER-ALIST
			    WHEN (MEMQ (CDR X) ACTIVE-LIST)
			    COLLECT (CAR X)))
    (COND ((NOT (EQUAL ACTIVE-LIST *OTHER-MAIL-FILE-NAMES*))
	   (SETQ *OTHER-MAIL-FILE-NAMES* ACTIVE-LIST)
	   (SETF (PROFILE-BUFFER-VARIABLE-TICK *INTERVAL*) (TICK))))))

))
