;;;-*-LISP-*-

(DEFSUBST LOGLDB-FROM-FIXNUM (PPSS WORD) (LDB PPSS WORD))

(DEFSUBST LOGDPB-INTO-FIXNUM (BYTE PPSS WORD) (DPB BYTE PPSS WORD))

(DEFSUBST LOGDPB (BYTE PPSS WORD) (DPB BYTE PPSS WORD))

(DEFMACRO 32-LOGAND (X Y) `(LOGAND ,X ,Y))

(DEFUN MASK-FIELD-FROM-FIXNUM (PPSS WORD)
   (LOGAND WORD (DPB -1 PPSS 0)))

(DEFUN LOGLDB (PPSS WORD) (COND ((>= (LOGAND PPSS 77) 30)
                                 (DPB (LDB (+ PPSS 2700 -27) WORD)
                                      2727
                                      (LDB (+ (LOGAND PPSS 7700) 27) WORD)))
                                (T (LDB PPSS WORD))))
